apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: haillion
build:
  artifacts:
    - image: haillion-billing
      context: .
      docker:
        dockerfile: services/billing/Dockerfile
    - image: haillion-gateway
      context: .
      docker:
        dockerfile: services/gateway/Dockerfile
    - image: haillion-identity
      context: .
      docker:
        dockerfile: services/identity/Dockerfile
    - image: haillion-matching
      context: .
      docker:
        dockerfile: services/matching/Dockerfile
    - image: haillion-notification
      context: .
      docker:
        dockerfile: services/notification/Dockerfile
    - image: haillion-review
      context: .
      docker:
        dockerfile: services/review/Dockerfile
    - image: haillion-trip
      context: .
      docker:
        dockerfile: services/trip/Dockerfile
manifests:
  rawYaml:
    - k8s/services/*.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: gateway
    namespace: haillion
    port: 8080
    localPort: 8080
