CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY,
    trip_id UUID NOT NULL,
    amount BIGINT NOT NULL,
    state VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
