#!/usr/bin/env bash
#
# gen-docs.sh — vendor LLM-friendly docs for the products this repo uses.
#
# Reads docs/manifest.tsv and writes one markdown snapshot per product into
# docs/vendor/, plus docs/vendor/INDEX.md. Agents read the vendored copies
# (and `go doc`) instead of paying for a live docs service per query.
#
# Source methods (see the manifest header):
#   llms-txt  curl an upstream llms.txt / llms-full.txt bundle
#   git-raw   curl a raw file from GitHub (works behind GitHub-only egress)
#   go-doc    run `go doc -all <import-path>`, pinned to go.mod's version
#   none      reference-only; recorded in the index, nothing fetched
#
# Design (sibling to gen-repo-map.sh): cheap, deterministic, free, safe to
# commit. A snapshot is rewritten only when its content changes, so reruns
# produce no git noise. Fetches that fail (blocked egress, 404, missing
# go.mod) are reported as MISS and leave any existing snapshot untouched —
# a transient block never wipes good docs.
#
# Run where outbound network is open (locally or CI). In this repo's sandbox
# only GitHub egress is allowed, so llms-txt rows MISS here by design.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MANIFEST="docs/manifest.tsv"
OUT="docs/vendor"
INDEX="$OUT/INDEX.md"

command -v curl >/dev/null 2>&1 || { echo "gen-docs: curl is required" >&2; exit 1; }
[ -f "$MANIFEST" ] || { echo "gen-docs: manifest not found: $MANIFEST" >&2; exit 1; }
mkdir -p "$OUT"

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

sha() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum | awk '{print $1}';
  else shasum -a 256 | awk '{print $1}'; fi
}
trim() { printf '%s' "$1" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//'; }
existing_body_sha() { [ -f "$1" ] && grep -m1 '^body-sha256:' "$1" | awk '{print $2}' || true; }

# Index accumulators (parallel arrays, manifest order = deterministic output).
IDX_NAME=(); IDX_METHOD=(); IDX_VER=(); IDX_STATUS=(); IDX_FILE=(); IDX_SOURCE=()
n_ok=0; n_miss=0; n_skip=0

# write_snapshot <name> <method> <source> <reference> <version> <bodyfile>
# Returns 0 if it (re)wrote the file, 1 if the body was unchanged.
write_snapshot() {
  local name="$1" method="$2" source="$3" ref="$4" version="$5" body="$6"
  local out="$OUT/${name}.md"
  local newsha oldsha
  newsha="$(sha < "$body")"
  oldsha="$(existing_body_sha "$out")"
  [ "$newsha" = "$oldsha" ] && return 1
  {
    echo "---"
    echo "name: ${name}"
    echo "method: ${method}"
    [ -n "$version" ] && echo "version: ${version}"
    echo "source: ${source}"
    [ -n "$ref" ] && echo "reference: ${ref}"
    echo "fetched-at: ${TS}"
    echo "body-sha256: ${newsha}"
    echo "---"
    echo "<!-- AUTO-GENERATED by scripts/gen-docs.sh — do not edit. Refresh: make docs -->"
    echo
    cat "$body"
  } > "$out"
  return 0
}

while IFS= read -r raw || [ -n "$raw" ]; do
  line="${raw%%#*}"
  line="$(trim "$line")"
  [ -z "$line" ] && continue

  IFS='|' read -r name method source ref <<<"$line"
  name="$(trim "$name")"; method="$(trim "$method")"
  source="$(trim "$source")"; ref="$(trim "$ref")"
  [ -z "$name" ] && continue

  case "$name" in
    *[!A-Za-z0-9._-]*) echo "gen-docs: skipping invalid name '$name'" >&2; continue ;;
  esac

  version=""; status=""; file="—"

  case "$method" in
    none)
      status="reference-only"; n_skip=$((n_skip+1)) ;;

    llms-txt|git-raw)
      tmp="$(mktemp)"
      if curl -fsSL --max-time 60 "$source" -o "$tmp" 2>/dev/null && [ -s "$tmp" ]; then
        if write_snapshot "$name" "$method" "$source" "$ref" "" "$tmp"; then
          status="OK (updated)"; else status="OK (unchanged)"; fi
        version="fetched ${TS%T*}"; file="[${name}.md](${name}.md)"; n_ok=$((n_ok+1))
      else
        status="MISS (fetch failed)"; n_miss=$((n_miss+1))
        [ -f "$OUT/${name}.md" ] && file="[${name}.md](${name}.md)"
      fi
      rm -f "$tmp" ;;

    go-doc)
      modinfo="$(go list -f '{{if .Module}}{{.Module.Path}} {{.Module.Version}}{{end}}' "$source" 2>/dev/null || true)"
      if [ -n "$modinfo" ]; then
        version="${modinfo#* }"
        tmp="$(mktemp)"
        if go doc -all "$source" >"$tmp" 2>/dev/null && [ -s "$tmp" ]; then
          if write_snapshot "$name" "$method" "$source" "$ref" "$version" "$tmp"; then
            status="OK (updated)"; else status="OK (unchanged)"; fi
          file="[${name}.md](${name}.md)"; n_ok=$((n_ok+1))
        else
          status="MISS (go doc failed)"; n_miss=$((n_miss+1))
        fi
        rm -f "$tmp"
      else
        status="MISS (not in go.mod)"; n_miss=$((n_miss+1))
      fi ;;

    *)
      echo "gen-docs: unknown method '$method' for '$name'" >&2
      status="MISS (unknown method)"; n_miss=$((n_miss+1)) ;;
  esac

  IDX_NAME+=("$name"); IDX_METHOD+=("$method"); IDX_VER+=("${version:-—}")
  IDX_STATUS+=("$status"); IDX_FILE+=("$file"); IDX_SOURCE+=("$source")
done < "$MANIFEST"

{
  echo "# Vendored documentation index"
  echo
  echo "> Auto-generated by \`scripts/gen-docs.sh\` at ${TS}. Do not edit."
  echo "> Source of truth: \`docs/manifest.tsv\`. Refresh with \`make docs\`."
  echo
  echo "| Product | Method | Version / Fetched | Status | Snapshot | Source |"
  echo "|---------|--------|-------------------|--------|----------|--------|"
  for i in "${!IDX_NAME[@]}"; do
    src="${IDX_SOURCE[$i]}"
    [ "$src" = "-" ] && src="—"
    printf '| %s | %s | %s | %s | %s | %s |\n' \
      "${IDX_NAME[$i]}" "${IDX_METHOD[$i]}" "${IDX_VER[$i]}" \
      "${IDX_STATUS[$i]}" "${IDX_FILE[$i]}" "$src"
  done
} > "$INDEX"

echo "gen-docs: ${n_ok} ok, ${n_miss} miss, ${n_skip} reference-only -> ${OUT}/ (see INDEX.md)" >&2
