#!/usr/bin/env bash
#
# gen-repo-map.sh — regenerate .opencode/maps/ from the current source tree.
#
# The repo map is the navigation aid sub-agents read before any source. This
# script regenerates it deterministically and for free (no model calls), so it
# is safe to run on every merge to main or on demand via /map.
#
# Outputs:
#   .opencode/maps/repo-map.md           top-level skeleton: services, shared
#                                        packages, and their public surface.
#   .opencode/maps/services/<svc>.md     per-service summary: public types and
#                                        functions with signatures, plus the
#                                        pkg/ and internal/ packages it imports.
#
# Design constraints (see README "gen-repo-map.sh"):
#   - Deterministic: same repo state => same map.
#   - Small: target <8k tokens top-level, <4k per service.
#   - Free: no embedded model calls.
#
# Accuracy comes from `go doc` (type-aware, resolves real signatures) and
# `go list` (authoritative package + import graph). A one-line human summary is
# preserved across regenerations from a `// repo-map:summary <text>` comment in
# the package.

set -euo pipefail

# Resolve repo root from this script's location so it runs from anywhere.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MAPS_DIR=".opencode/maps"
SERVICES_MAPS_DIR="$MAPS_DIR/services"
REPO_MAP="$MAPS_DIR/repo-map.md"

mkdir -p "$SERVICES_MAPS_DIR"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "gen-repo-map: required tool not found: $1" >&2
    exit 1
  }
}
require go

# Module path, if a module exists yet. Without a go.mod, `go list -m` prints the
# synthetic "command-line-arguments" sentinel; treat that as no module.
MODULE="$(go list -m 2>/dev/null || true)"
[ "$MODULE" = "command-line-arguments" ] && MODULE=""

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Extract the preserved one-line summary for a package directory, if present.
pkg_summary() {
  local dir="$1"
  local line
  line="$(grep -rhoE '//[[:space:]]*repo-map:summary.*' "$dir" 2>/dev/null | head -n1 || true)"
  [ -n "$line" ] && printf '%s' "${line#*repo-map:summary}" | sed -E 's/^[[:space:]]+//'
}

# pkg/ and internal/ imports of a package, one per line, module-relative.
coupled_imports() {
  local importpath="$1"
  [ -n "$MODULE" ] || return 0
  go list -f '{{ range .Imports }}{{ . }}{{ "\n" }}{{ end }}' "$importpath" 2>/dev/null \
    | grep -E "^${MODULE}/(pkg|internal)/" \
    | sed -E "s#^${MODULE}/#  - #" \
    | sort -u || true
}

# Append the public surface (types + funcs with signatures) for a package.
write_surface() {
  local importpath="$1"
  local out="$2"
  local doc
  doc="$(go doc -short "$importpath" 2>/dev/null || true)"
  if [ -z "$doc" ]; then
    echo "_No exported symbols._" >> "$out"
    return 0
  fi
  {
    echo '```go'
    printf '%s\n' "$doc"
    echo '```'
  } >> "$out"
}

# Enumerate package import paths under a top-level dir (e.g. services, pkg).
pkgs_under() {
  local top="$1"
  [ -n "$MODULE" ] || return 0
  [ -d "$top" ] || return 0
  go list "./${top}/..." 2>/dev/null || true
}

# --- top-level map -----------------------------------------------------------
{
  echo "# Repo map"
  echo
  echo "> Auto-generated by \`scripts/gen-repo-map.sh\`. Do not edit by hand."
  echo "> Generated at ${GENERATED_AT}."
  echo
  if [ -z "$MODULE" ]; then
    echo "No Go module found yet (\`go list -m\` returned nothing)."
    echo "Add a root \`go.mod\` and source under \`services/\` and \`pkg/\`, then rerun."
  else
    echo "Module: \`${MODULE}\`"
  fi
  echo
  echo "## Services"
  echo
} > "$REPO_MAP"

if [ -n "$MODULE" ] && [ -d services ]; then
  # One per-service file, and a top-level index entry referencing it.
  for svc_dir in services/*/; do
    [ -d "$svc_dir" ] || continue
    svc="$(basename "$svc_dir")"
    svc_map="$SERVICES_MAPS_DIR/${svc}.md"
    summary="$(pkg_summary "$svc_dir")"

    {
      echo "# Service: ${svc}"
      echo
      echo "> Auto-generated by \`scripts/gen-repo-map.sh\`. Do not edit by hand."
      echo "> Generated at ${GENERATED_AT}."
      echo
      [ -n "$summary" ] && { echo "$summary"; echo; }
    } > "$svc_map"

    while IFS= read -r importpath; do
      [ -n "$importpath" ] || continue
      rel="${importpath#"$MODULE"/}"
      {
        echo "## \`${rel}\`"
        echo
      } >> "$svc_map"
      write_surface "$importpath" "$svc_map"
      imports="$(coupled_imports "$importpath")"
      if [ -n "$imports" ]; then
        {
          echo
          echo "Imports (pkg/ + internal/):"
          echo "$imports"
        } >> "$svc_map"
      fi
      echo >> "$svc_map"
    done < <(pkgs_under "services/${svc}")

    {
      if [ -n "$summary" ]; then
        echo "- **${svc}** — ${summary} ([map](services/${svc}.md))"
      else
        echo "- **${svc}** ([map](services/${svc}.md))"
      fi
    } >> "$REPO_MAP"
  done
else
  echo "_None._" >> "$REPO_MAP"
fi

{
  echo
  echo "## Shared packages (\`pkg/\`)"
  echo
} >> "$REPO_MAP"

if [ -n "$MODULE" ] && [ -d pkg ]; then
  while IFS= read -r importpath; do
    [ -n "$importpath" ] || continue
    rel="${importpath#"$MODULE"/}"
    dir="${importpath#"$MODULE"/}"
    summary="$(pkg_summary "$dir")"
    {
      if [ -n "$summary" ]; then
        echo "### \`${rel}\` — ${summary}"
      else
        echo "### \`${rel}\`"
      fi
      echo
    } >> "$REPO_MAP"
    write_surface "$importpath" "$REPO_MAP"
    echo >> "$REPO_MAP"
  done < <(pkgs_under pkg)
else
  echo "_None._" >> "$REPO_MAP"
fi

echo "gen-repo-map: wrote ${REPO_MAP} and per-service maps under ${SERVICES_MAPS_DIR}/" >&2
